name: CI

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.HUB_DOCKER_USER_NAME }}
          password: ${{ secrets.HUB_DOCKER_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: |
            padevdocker/api-ts:1.0.1
            padevdocker/api-ts:latest
